/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package dao;
import javax.swing.JOptionPane;


public class Tables {
    public static void main(String[] args) {
        try {
            
            String AppUser = "DECLARE COUNT_NUM INT:=0; BEGIN SELECT COUNT(TABLE_NAME) INTO COUNT_NUM FROM USER_TABLES WHERE TABLE_NAME='APPUSER';"
                    + "IF COUNT_NUM <= 0 THEN EXECUTE IMMEDIATE 'CREATE TABLE AppUser ("
                    + "AppUserID INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,"
                    + "Username VARCHAR2(100) NOT NULL,"
                    + "UserPassword VARCHAR2(100) NOT NULL,"
                    + "UserRole VARCHAR2(100) NOT NULL,"
                    + "CONSTRAINT AppUser_PK PRIMARY KEY (AppUserID))'; "
                    + "END IF;"
                    + "END;";
            
            String adminDetails = "INSERT INTO AppUser("
                    + "AppUserID,"
                    + "Username,"
                    + "UserPassword,"
                    + "UserRole )" 
                    + "VALUES ("
                    + "3000,"
                    + "'Admin',"
                    + "'Admin',"
                    + "'Admin')";
            
            String Restaurant = "DECLARE COUNT_NUM INT:=0; BEGIN SELECT COUNT(TABLE_NAME) INTO COUNT_NUM FROM USER_TABLES WHERE TABLE_NAME='RESTAURANT';"
                    + "IF COUNT_NUM <= 0 THEN EXECUTE IMMEDIATE 'CREATE TABLE Restaurant ("
                    + "RestaurantID INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,"
                    + "RestaurantAddress VARCHAR2(100) NOT NULL,"
                    + "RestaurantName VARCHAR2(100) NOT NULL,"
                    + "RestaurantPhone INTEGER NOT NULL,"
                    + "CONSTRAINT Restaurant_PK PRIMARY KEY (RestaurantID))'; "
                    + "END IF;"
                    + "END;";

            String Client = "DECLARE COUNT_NUM INT:=0; BEGIN SELECT COUNT(TABLE_NAME) INTO COUNT_NUM FROM USER_TABLES WHERE TABLE_NAME='CLIENT';"
                    + "IF COUNT_NUM <= 0 THEN EXECUTE IMMEDIATE 'CREATE TABLE Client ("
                    + "ClientID INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,"
                    + "ClientName VARCHAR2(100) NOT NULL,"
                    + "ClientSurname VARCHAR2(100) NOT NULL,"
                    + "ClientPhoneNo INTEGER NOT NULL,"
                    + "ClientEmail VARCHAR2(100) NOT NULL,"
                    + "ClientUsername VARCHAR2(100) NOT NULL,"
                    + "ClientPassword VARCHAR2(100) NOT NULL,"
                    + "CONSTRAINT Client_PK PRIMARY KEY (ClientID))'; "
                    + "END IF;"
                    + "END;";

            String Meal = "DECLARE COUNT_NUM INT:=0; BEGIN SELECT COUNT(TABLE_NAME) INTO COUNT_NUM FROM USER_TABLES WHERE TABLE_NAME='MEAL';"
                    + "IF COUNT_NUM <= 0 THEN EXECUTE IMMEDIATE 'CREATE TABLE Meal ("
                    + "MealID INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,"
                    + "MealName VARCHAR2(100) NOT NULL,"
                    + "MealDescription VARCHAR2(250) NOT NULL,"
                    + "MealPrice FLOAT NOT NULL,"
                    + "CONSTRAINT Meal_PK PRIMARY KEY (MealID))'; "
                    + "END IF;"
                    + "END;";

            String Orders = "DECLARE COUNT_NUM INT:=0; BEGIN SELECT COUNT(TABLE_NAME) INTO COUNT_NUM FROM USER_TABLES WHERE TABLE_NAME='ORDERS';"
                    + "IF COUNT_NUM <= 0 THEN EXECUTE IMMEDIATE 'CREATE TABLE Orders ("
                    + "OrderID INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,"
                    + "ClientID INTEGER NOT NULL,"
                    + "OrderDate DATE NOT NULL,"
                    + "Status VARCHAR2(100) NOT NULL,"
                    + "CONSTRAINT Orders_PK PRIMARY KEY (OrderID),"
                    + "CONSTRAINT Orders_FK_Client FOREIGN KEY (ClientID) REFERENCES Client(ClientID))'; "
                    + "END IF;"
                    + "END;";

            String OrderItems = "DECLARE COUNT_NUM INT:=0; BEGIN SELECT COUNT(TABLE_NAME) INTO COUNT_NUM FROM USER_TABLES WHERE TABLE_NAME='ORDERITEMS';"
                    + "IF COUNT_NUM <= 0 THEN EXECUTE IMMEDIATE 'CREATE TABLE OrderItems ("
                    + "OrderItemsID INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,"
                    + "OrderID INTEGER NOT NULL,"
                    + "MealID INTEGER NOT NULL,"
                    + "ClientID INTEGER NOT NULL,"
                    + "NumberOfPlatesOrder INTEGER NOT NULL,"
                    + "CONSTRAINT OrderItems_PK PRIMARY KEY (OrderItemsID),"
                    + "CONSTRAINT MM FOREIGN KEY (OrderID) REFERENCES Orders(OrderID),"
                    + "CONSTRAINT OrderItems_FK_Meal FOREIGN KEY (MealID) REFERENCES Meal(MealID),"
                    + "CONSTRAINT OrderItems_FK_Client FOREIGN KEY (ClientID) REFERENCES Client(ClientID))'; "
                    + "END IF;"
                    + "END;";

            String RestaurantMeal = "DECLARE COUNT_NUM INT:=0; BEGIN SELECT COUNT(TABLE_NAME) INTO COUNT_NUM FROM USER_TABLES WHERE TABLE_NAME='RESTAURANTMEAL';"
                    + "IF COUNT_NUM <= 0 THEN EXECUTE IMMEDIATE 'CREATE TABLE RestaurantMeal ("
                    + "RestaurantMealID INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,"
                    + "MealID INTEGER NOT NULL,"
                    + "RestaurantID INTEGER NOT NULL,"
                    + "CONSTRAINT RestaurantMeal_PK PRIMARY KEY (RestaurantMealID),"
                    + "CONSTRAINT RestaurantMeal_FK_Meal FOREIGN KEY (MealID) REFERENCES Meal(MealID),"
                    + "CONSTRAINT RestaurantMeal_FK_Restaurant FOREIGN KEY (RestaurantID) REFERENCES Restaurant(RestaurantID))'; "
                    + "END IF;"
                    + "END;";

            
            String OrderRestaurant = "DECLARE COUNT_NUM INT:=0; BEGIN SELECT COUNT(TABLE_NAME) INTO COUNT_NUM FROM USER_TABLES WHERE TABLE_NAME='ORDERRESTAURANT';"
                    + "IF COUNT_NUM <= 0 THEN EXECUTE IMMEDIATE 'CREATE TABLE OrderRestaurant ("
                    + "OrderRestaurantID INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,"
                    + "OrderID INTEGER NOT NULL,"
                    + "RestaurantID INTEGER NOT NULL,"
                    + "CONSTRAINT OrderRestaurant_PK PRIMARY KEY (OrderRestaurantID),"
                    + "CONSTRAINT OrderRestaurant_FK_Order FOREIGN KEY (OrderID) REFERENCES Orders(OrderID), "
                    + "CONSTRAINT OrderRestaurant_FK_Restaurant FOREIGN KEY (RestaurantID) REFERENCES Restaurant(RestaurantID))';"
                    + "END IF;"
                    + "END;";

            // Execute the statements for each table
            DbMgmt.setDataorDelete(AppUser, "AppUser Table Created Successfully");
            DbMgmt.setDataorDelete(adminDetails, "Admin User Inserted Successfully");
            DbMgmt.setDataorDelete(Restaurant, "Restaurant Table Created Successfully");
            DbMgmt.setDataorDelete(Client, "Client Table Created Successfully");
            DbMgmt.setDataorDelete(Meal, "Meal Table Created Successfully");
            DbMgmt.setDataorDelete(Orders, "Orders Table Created Successfully");
            DbMgmt.setDataorDelete(OrderItems, "OrderItems Table Created Successfully");
            DbMgmt.setDataorDelete(RestaurantMeal, "RestaurantMeal Table Created Successfully");
            DbMgmt.setDataorDelete(OrderRestaurant, "OrderRestaurant Table Created Successfully");


        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
}